# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


yelp_consumer_key: "VTuV_f_P9oDTGJHEAsh-7Q"
yelp_consumer_secret: "jmsVWhC7D1YTMHXTt7mf9x5g4Fs"
yelp_token: "Pmk35JV-ParB5QXtYuwluJF-BmkHKg2g"
yelp_token_secret: "45n6ZsM-CCvDCdMwpG-RTiWkJhc"


test:
  yelp_consumer_key: "VTuV_f_P9oDTGJHEAsh-7Q"
  yelp_consumer_secret: "jmsVWhC7D1YTMHXTt7mf9x5g4Fs"
  yelp_token: "Pmk35JV-ParB5QXtYuwluJF-BmkHKg2g"
  yelp_token_secret: "45n6ZsM-CCvDCdMwpG-RTiWkJhc"