# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d6a13ea82eea4b55dcfff0f64be9d9ddcd3cae4003eaeaf575ba232f6cd591396a8356cc2f9e13967ae6c7061ced4a42abfc986469961bd42c2df81c6e4cd1c

test:
  secret_key_base: bca51917d5f2fd2ebfbdc5d8624a44c2181c56456dc9b9c4b897ef45f4c6ee14988f41e4eaa663ed2bed2be6e1f7aa72c9274c9b39f64d6c0ab2602de9971527

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
